######################## default configuration ####################
baseURL = "https://informaticaan.github.io/mi-blog-DAR/"
languageCode = "es"
title = "Mi blog de recetas"
theme = ""
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"
[[params.plugins.css]]
URL = "css/hojaEstilos.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Inicio"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 2

[[menu.main]]
name = "Sobre mí"
URL = "about-us"
weight = 3

[[menu.main]]
name = "Contacto"
URL = "contact-us"
weight = 4


#################### default parameters ################################
[params]
logo = "images/logoBlog.jpg"
# meta data
author = "Elisa"
description = "Blog de recetas"
# google analitycs ID
google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

